export const STORAGE_KEY = 'sifos-site-survey-v1'

export const CATEGORIES = [
  { id: 'cctv', label: 'CCTV Camera', icon: '📹' },
  { id: 'nvr', label: 'NVR / DVR Storage', icon: '💾' },
  { id: 'access', label: 'Access Control', icon: '🚪' },
  { id: 'attendance', label: 'Attendance', icon: '👤' },
  { id: 'machine', label: 'Production Machine', icon: '⚙️' },
  { id: 'inventory', label: 'Inventory', icon: '📦' },
  { id: 'sensor', label: 'Environmental Sensor', icon: '🌡️' },
  { id: 'asset', label: 'Laptop / Asset', icon: '💻' },
  { id: 'network', label: 'Network / Gateway', icon: '🌐' },
  { id: 'conference', label: 'Conference Call', icon: '📞' },
  { id: 'glossary', label: 'Abbreviations', icon: '📖' },
]

export const ABBREVIATIONS = [
  { term: 'SIFOS', meaning: 'Smart Integrated Factory Operations System — the web platform you are building.' },
  { term: 'CCTV', meaning: 'Closed-Circuit Television — security cameras on the factory site.' },
  { term: 'NVR', meaning: 'Network Video Recorder — box that records camera footage on site.' },
  { term: 'DVR', meaning: 'Digital Video Recorder — older type of recorder for cameras (often coax cables).' },
  { term: 'PoE', meaning: 'Power over Ethernet — camera gets power through the same network cable.' },
  { term: 'RTSP', meaning: 'Real Time Streaming Protocol — standard way to pull live video from cameras/NVR.' },
  { term: 'ONVIF', meaning: 'Open standard so different camera brands can work with software.' },
  { term: 'API', meaning: 'Application Programming Interface — how software talks to a device remotely.' },
  { term: 'SDK', meaning: 'Software Development Kit — tools from the device maker for integration.' },
  { term: 'RFID', meaning: 'Radio-Frequency ID — card or tag used for door access or attendance.' },
  { term: 'PLC', meaning: 'Programmable Logic Controller — industrial computer on a machine.' },
  { term: 'HMI', meaning: 'Human-Machine Interface — touch screen on a machine.' },
  { term: 'OEE', meaning: 'Overall Equipment Effectiveness — machine efficiency score (Availability × Performance × Quality).' },
  { term: 'WIP', meaning: 'Work In Progress — partly finished products on the production line.' },
  { term: 'UPS', meaning: 'Uninterruptible Power Supply — battery backup if power cuts.' },
  { term: 'RAID', meaning: 'Redundant Array of Independent Disks — multiple hard drives for safer storage (checklist had typo “RAFT”).' },
  { term: 'DHCP', meaning: 'Dynamic Host Configuration Protocol — router assigns IP addresses automatically.' },
  { term: 'IP', meaning: 'Internet Protocol address — unique number for each device on the network.' },
  { term: 'LAN', meaning: 'Local Area Network — wired network inside the factory building.' },
  { term: 'WiFi', meaning: 'Wireless network inside the factory.' },
  { term: 'VPN', meaning: 'Virtual Private Network — secure tunnel to connect remote sites.' },
  { term: 'HTTPS', meaning: 'Secure web connection — required for cloud integration.' },
  { term: 'AWS', meaning: 'Amazon Web Services — cloud platform in the Owner’s architecture diagram.' },
  { term: 'ERP', meaning: 'Enterprise Resource Planning — finance, accounts, and business records system.' },
  { term: 'CSV', meaning: 'Comma-Separated Values — spreadsheet file you can export from the app.' },
  { term: 'JSON', meaning: 'JavaScript Object Notation — structured data file for backup/export.' },
  { term: 'RS485', meaning: 'Industrial wiring protocol — common on access control and sensors.' },
  { term: 'Wiegand', meaning: 'Wiring standard between card reader and door controller.' },
  { term: 'I/O', meaning: 'Input/Output — electrical signals from machines (run/stop/fault).' },
  { term: 'PTZ', meaning: 'Pan-Tilt-Zoom — camera that can move and zoom remotely.' },
  { term: 'IR', meaning: 'Infrared — night vision on cameras.' },
  { term: 'TB', meaning: 'Terabyte — storage size (1 TB ≈ 1,000 GB of video storage).' },
  { term: 'Mbps', meaning: 'Megabits per second — internet speed (important for Starlink upload).' },
  { term: 'LTE', meaning: 'Long-Term Evolution — mobile/4G internet connection.' },
  { term: 'WAT', meaning: 'West Africa Time — Nigeria timezone (UTC+1).' },
  { term: 'SMS', meaning: 'Text message — optional future alert channel.' },
  { term: 'IoT', meaning: 'Internet of Things — connected devices sending data over the network.' },
  { term: 'QA', meaning: 'Quality Assurance — quality control department/process.' },
  { term: 'USB', meaning: 'Port for flash drives — some attendance devices export via USB.' },
  { term: 'PIN', meaning: 'Personal Identification Number — numeric code for door access.' },
  { term: 'TBD', meaning: 'To Be Determined — decision not made yet.' },
  { term: 'Med', meaning: 'Medium priority — important but not urgent for launch.' },
]

export const WALK_AREAS = [
  'Main gate / perimeter',
  'Reception / admin',
  'Production Hall A',
  'Production Hall B',
  'Packaging / finishing',
  'Raw materials store',
  'Finished goods warehouse',
  'Spare parts store',
  'Quality / lab',
  'Security / guard post',
  'NVR / server room',
  'External areas',
]

export const CONFERENCE_ITEMS = [
  { key: 'diagramComplete', label: 'All systems in Owner diagram are present at Ikeduru' },
  { key: 'awsPlan', label: 'AWS for CCTV storage + ERP confirmed (or alternative agreed)' },
  { key: 'ownerAustralia', label: 'Owner login from Australia is primary use case' },
  { key: 'remoteUnlock', label: 'Remote door unlock required at launch' },
  { key: 'liveCctvWeb', label: 'Live CCTV in web browser required (not alerts only)' },
  { key: 'cameraCount', label: 'Camera count and NVR model confirmed with engineer' },
  { key: 'rtspOnvif', label: 'RTSP or ONVIF available for cameras' },
  { key: 'engineerCredentials', label: 'Engineer can provide admin access or API docs' },
  { key: 'bandwidthOk', label: 'Starlink/internet upload enough for live video' },
  { key: 'recordingLocation', label: 'Recording local, cloud, or both — agreed' },
  { key: 'firewallPorts', label: 'Who opens firewall ports if needed' },
  { key: 'engineerTimeline', label: 'Engineer support timeline agreed' },
  { key: 'siteGateway', label: 'Site gateway PC on LAN (24/7) approved' },
  { key: 'itContact', label: 'Factory IT contact confirmed' },
  { key: 'electrician', label: 'Electrician for machine signals identified' },
  { key: 'physicalChanges', label: 'Who approves changes to doors/machines' },
  { key: 'ownerEmail', label: 'Owner production email collected' },
  { key: 'goLiveDate', label: 'Target go-live date agreed' },
  { key: 'alertChannels', label: 'Urgent alert channels discussed (SMS/email/WhatsApp)' },
  { key: 'timezone', label: 'Operating hours / timezone (WAT vs Australia) agreed' },
]

const yesNoUnknown = [
  { value: 'yes', label: 'Yes' },
  { value: 'no', label: 'No' },
  { value: 'unknown', label: 'Unknown' },
]

const yesNo = [
  { value: 'yes', label: 'Yes' },
  { value: 'no', label: 'No' },
]

const priority = [
  { value: 'high', label: 'High' },
  { value: 'med', label: 'Medium' },
  { value: 'low', label: 'Low' },
]

export const UNIVERSAL_FIELDS = [
  { key: 'area', label: 'Area / Location', type: 'text', required: true },
  { key: 'deviceName', label: 'Device / Machine name', type: 'text', required: true },
  { key: 'brand', label: 'Brand', type: 'text' },
  { key: 'model', label: 'Model', type: 'text' },
  { key: 'serialNumber', label: 'Serial number', type: 'text' },
  { key: 'quantity', label: 'Quantity', type: 'number' },
  { key: 'measuresControls', label: 'What it measures or controls', type: 'textarea' },
  { key: 'howUsedToday', label: 'How staff use it today', type: 'textarea' },
  { key: 'responsible', label: 'Who is responsible (name/role)', type: 'text' },
  { key: 'powerSource', label: 'Power source', type: 'select', options: ['Mains', 'PoE', 'Battery', 'Other'] },
  { key: 'installedAge', label: 'Installed date / age (approx)', type: 'text' },
  { key: 'condition', label: 'Working condition', type: 'select', options: ['Good', 'Faulty', 'Unknown'] },
  { key: 'networkConnect', label: 'Can it connect to network?', type: 'select', options: yesNoUnknown.map((o) => o.label) },
  { key: 'connectionType', label: 'Connection type', type: 'select', options: ['Ethernet', 'WiFi', 'RS485', 'Relay/I/O', 'Proprietary cable', 'Not connectable', 'Other'] },
  { key: 'hasApi', label: 'Has API / SDK / open protocol?', type: 'select', options: ['Yes', 'No', 'Unknown', 'Ask Engineer'] },
  { key: 'protocolSoftware', label: 'Protocol / software (if known)', type: 'text' },
  { key: 'engineerNotes', label: 'Integration notes from engineer', type: 'textarea' },
  { key: 'photoDevice', label: 'Photo of device taken?', type: 'select', options: yesNo.map((o) => o.label) },
  { key: 'photoPanel', label: 'Photo of control panel taken?', type: 'select', options: yesNo.map((o) => o.label) },
  { key: 'photoNameplate', label: 'Photo of nameplate taken?', type: 'select', options: yesNo.map((o) => o.label) },
  { key: 'photoNetwork', label: 'Photo of network port/cable taken?', type: 'select', options: yesNo.map((o) => o.label) },
  { key: 'priority', label: 'Priority', type: 'select', options: priority.map((o) => o.label) },
  { key: 'liveAtLaunch', label: 'Must be live in SIFOS at launch?', type: 'select', options: yesNo.map((o) => o.label) },
  { key: 'remoteControl', label: 'Owner wants remote control/view?', type: 'select', options: ['Yes', 'No', 'View only'] },
  { key: 'notes', label: 'Notes', type: 'textarea' },
]

export const CATEGORY_FIELDS = {
  cctv: [
    { key: 'cameraType', label: 'Camera type', type: 'select', options: ['Dome', 'Bullet', 'PTZ', 'Other'] },
    { key: 'indoorOutdoor', label: 'Indoor / Outdoor', type: 'select', options: ['Indoor', 'Outdoor'] },
    { key: 'mounting', label: 'Mounting height & angle', type: 'text' },
    { key: 'coverage', label: 'Coverage area (what it sees)', type: 'textarea' },
    { key: 'resolution', label: 'Resolution (1080p / 4MP / 4K)', type: 'text' },
    { key: 'nightVision', label: 'Night vision / IR', type: 'select', options: yesNo.map((o) => o.label) },
    { key: 'audio', label: 'Audio (mic/speaker)', type: 'select', options: yesNo.map((o) => o.label) },
    { key: 'poePower', label: 'PoE or separate power', type: 'text' },
    { key: 'nvrChannel', label: 'NVR channel #', type: 'text' },
    { key: 'localApp', label: 'Local viewing app/software', type: 'text' },
    { key: 'remoteViewing', label: 'Remote viewing already working?', type: 'select', options: yesNoUnknown.map((o) => o.label) },
    { key: 'rtspOnvif', label: 'RTSP / ONVIF supported?', type: 'select', options: ['Yes', 'No', 'Unknown'] },
    { key: 'sifosStream', label: 'Need in SIFOS web app', type: 'select', options: ['Live stream', 'Snapshots only', 'Alerts only'] },
    { key: 'retentionDays', label: 'Recording retention (days)', type: 'number' },
  ],
  nvr: [
    { key: 'channelsUsed', label: 'Channels used', type: 'text' },
    { key: 'channelsTotal', label: 'Channels total', type: 'text' },
    { key: 'storageTb', label: 'Storage capacity (TB)', type: 'text' },
    { key: 'raidHdd', label: 'RAID / HDD count', type: 'text' },
    { key: 'cloudUpload', label: 'Cloud upload today?', type: 'select', options: yesNo.map((o) => o.label) },
    { key: 'nvrLocation', label: 'NVR physical location', type: 'text' },
    { key: 'ups', label: 'UPS backup on NVR?', type: 'select', options: yesNo.map((o) => o.label) },
    { key: 'ipConfig', label: 'Static IP or DHCP on LAN', type: 'text' },
    { key: 'adminAccess', label: 'Admin access — who has login', type: 'text' },
    { key: 'apiAccess', label: 'API / SDK / RTSP gateway access?', type: 'select', options: ['Yes', 'No', 'Unknown'] },
    { key: 'awsPlanned', label: 'AWS storage planned by owner?', type: 'select', options: ['Yes', 'No', 'Discuss on call'] },
  ],
  access: [
    { key: 'accessPointName', label: 'Access point name (for SIFOS)', type: 'text' },
    { key: 'doorType', label: 'Door type', type: 'select', options: ['Swing', 'Sliding', 'Turnstile', 'Gate', 'Roller shutter'] },
    { key: 'entryMethod', label: 'Entry method today', type: 'select', options: ['Key', 'RFID card', 'Fingerprint', 'Face', 'PIN', 'Guard'] },
    { key: 'controllerBrand', label: 'Controller brand/model', type: 'text' },
    { key: 'readerBrand', label: 'Reader brand/model', type: 'text' },
    { key: 'remoteUnlock', label: 'Can unlock remotely?', type: 'select', options: yesNoUnknown.map((o) => o.label) },
    { key: 'lockType', label: 'Lock type (maglock/strike/motor)', type: 'text' },
    { key: 'failSafe', label: 'Fail-safe or fail-secure', type: 'text' },
    { key: 'entryLog', label: 'Log of entries today?', type: 'select', options: ['Yes', 'No', 'Paper only'] },
    { key: 'usersEnrolled', label: 'Number of users enrolled', type: 'number' },
    { key: 'integration', label: 'Integration (Wiegand/RS485/IP)', type: 'text' },
  ],
  attendance: [
    { key: 'deviceType', label: 'Device type', type: 'select', options: ['Fingerprint', 'Face', 'RFID', 'Mobile app', 'Manual register'] },
    { key: 'deviceCount', label: 'Number of devices & locations', type: 'text' },
    { key: 'staffEnrolled', label: 'Staff enrolled (approx)', type: 'number' },
    { key: 'shiftPatterns', label: 'Shift patterns (times)', type: 'text' },
    { key: 'exportMethod', label: 'Exports data how?', type: 'select', options: ['USB', 'Excel', 'Software', 'Cloud', 'None'] },
    { key: 'softwareName', label: 'Software name', type: 'text' },
    { key: 'networkPush', label: 'Can push to network/API?', type: 'select', options: yesNoUnknown.map((o) => o.label) },
    { key: 'lateAbsentRules', label: 'Late / absent rules owner expects', type: 'textarea' },
  ],
  machine: [
    { key: 'lineLocation', label: 'Line / hall location', type: 'text' },
    { key: 'yearInstalled', label: 'Year installed', type: 'text' },
    { key: 'statusSignals', label: 'Status signals available', type: 'text', placeholder: 'Running, Idle, Fault, Maintenance, None' },
    { key: 'outputCount', label: 'Output count available?', type: 'select', options: ['Yes', 'No', 'Manual only'] },
    { key: 'outputUnit', label: 'Output unit (pieces/kg/cycles)', type: 'text' },
    { key: 'plcHmi', label: 'PLC / HMI brand', type: 'text' },
    { key: 'hmiOee', label: 'HMI shows OEE?', type: 'select', options: yesNo.map((o) => o.label) },
    { key: 'maintenanceSchedule', label: 'Maintenance schedule today', type: 'select', options: ['Paper', 'Excel', 'None'] },
    { key: 'targetOutput', label: 'Target output per shift', type: 'text' },
    { key: 'operatorShift', label: 'Operator name / shift', type: 'text' },
    { key: 'electricianTap', label: 'Electrician signal tap possible?', type: 'select', options: ['Yes', 'No', 'TBD'] },
  ],
  inventory: [
    { key: 'trackedItems', label: 'What is tracked', type: 'text', placeholder: 'Raw materials, WIP, Finished goods, Spare parts' },
    { key: 'storageLocation', label: 'Storage location name', type: 'text' },
    { key: 'trackingMethod', label: 'Tracking method today', type: 'select', options: ['Paper', 'Excel', 'Software', 'Visual only'] },
    { key: 'inventorySoftware', label: 'Software name', type: 'text' },
    { key: 'barcodeUsed', label: 'Barcode / QR / RFID used?', type: 'select', options: yesNo.map((o) => o.label) },
    { key: 'scalesBrand', label: 'Weighing scales brand', type: 'text' },
    { key: 'stockUpdater', label: 'Who updates stock (role)', type: 'text' },
    { key: 'reorderAlerts', label: 'Reorder alerts needed?', type: 'select', options: yesNo.map((o) => o.label) },
    { key: 'lowStockItems', label: 'Typical low-stock items', type: 'textarea' },
  ],
  sensor: [
    { key: 'sensorType', label: 'Sensor type', type: 'select', options: ['Temperature', 'Humidity', 'Air quality', 'Noise', 'Dust', 'Other'] },
    { key: 'mountLocation', label: 'Mounting location', type: 'text' },
    { key: 'wiredWireless', label: 'Wired or wireless', type: 'text' },
    { key: 'readingMethod', label: 'Current reading method', type: 'select', options: ['Manual', 'Local display', 'Network', 'None'] },
    { key: 'acceptableRange', label: 'Min / max acceptable range', type: 'text' },
    { key: 'alertWho', label: 'Alert who when out of range', type: 'text' },
    { key: 'calibrationDate', label: 'Calibration / last service date', type: 'text' },
    { key: 'batteryLife', label: 'Battery-powered? Battery life', type: 'text' },
  ],
  asset: [
    { key: 'assetType', label: 'Asset type', type: 'select', options: ['Laptop', 'Desktop', 'Tablet', 'Printer', 'Tool', 'Other'] },
    { key: 'assignedTo', label: 'Assigned to (name/dept)', type: 'text' },
    { key: 'assetTag', label: 'Asset tag / serial', type: 'text' },
    { key: 'assetCondition', label: 'Condition', type: 'select', options: ['Good', 'Fair', 'Poor'] },
    { key: 'usedFor', label: 'Used for production / office / both', type: 'text' },
    { key: 'trackInSifos', label: 'Track in SIFOS Assets module?', type: 'select', options: yesNo.map((o) => o.label) },
  ],
  network: [
    { key: 'internetProvider', label: 'Internet provider', type: 'select', options: ['Starlink', 'Fiber', 'LTE', 'Other'] },
    { key: 'downloadMbps', label: 'Download speed (Mbps)', type: 'text' },
    { key: 'uploadMbps', label: 'Upload speed (Mbps)', type: 'text' },
    { key: 'wifiCoverage', label: 'WiFi on production floor', type: 'select', options: ['Good', 'Partial', 'Poor', 'None'] },
    { key: 'wifiBrand', label: 'Enterprise WiFi brand', type: 'text' },
    { key: 'switchInfo', label: 'LAN switch brand / port count', type: 'text' },
    { key: 'firewallModel', label: 'Firewall / router brand & model', type: 'text' },
    { key: 'networkManager', label: 'Who manages network (name/phone)', type: 'text' },
    { key: 'cloudHttps', label: 'Devices can reach cloud HTTPS?', type: 'select', options: yesNoUnknown.map((o) => o.label) },
    { key: 'publicIp', label: 'Static or dynamic public IP', type: 'text' },
    { key: 'vpnInUse', label: 'VPN already in use?', type: 'select', options: yesNo.map((o) => o.label) },
    { key: 'gatewaySpace', label: 'Space for site gateway PC (24/7)?', type: 'select', options: ['Yes', 'No', 'Location noted in notes'] },
    { key: 'photoRack', label: 'Photo of rack/router/switch taken?', type: 'select', options: yesNo.map((o) => o.label) },
  ],
}

export function getFieldsForCategory(categoryId) {
  if (categoryId === 'conference' || categoryId === 'glossary') return []
  return [...UNIVERSAL_FIELDS, ...(CATEGORY_FIELDS[categoryId] || [])]
}

export function emptyForm(categoryId) {
  const fields = getFieldsForCategory(categoryId)
  return fields.reduce((acc, field) => {
    acc[field.key] = field.type === 'number' ? '' : ''
    return acc
  }, { category: categoryId })
}
